import { defineConfig } from 'bunup'

export default defineConfig({
	entry: [
		'./src/cli/index.ts',
		'./src/compression/index.ts',
		'./src/concurrency/index.ts',
		'./src/errors/index.ts',
		'./src/formatters/index.ts',
		'./src/fs/index.ts',
		'./src/geo/index.ts',
		'./src/git/index.ts',
		'./src/glob/index.ts',
		'./src/hash/index.ts',
		'./src/html/index.ts',
		'./src/instrumentation/index.ts',
		'./src/logging/index.ts',
		'./src/mcp/index.ts',
		'./src/oauth/index.ts',
		'./src/password/index.ts',
		'./src/slo/index.ts',
		'./src/spawn/index.ts',
		'./src/streams/index.ts',
		'./src/terminal/index.ts',
		'./src/testing/index.ts',
		'./src/utils/index.ts',
		'./src/validation/index.ts',
		'./src/vtt/index.ts',
		'./src/mcp-response/index.ts',
	],
	outDir: './dist',
	target: 'bun',
	format: 'esm',
	dts: true,
	clean: true,
	splitting: true,
})
